# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.1
        with:
          #
          github-token: ${{ github.token }}
          # Path to lcov file
          path-to-lcov: ./packages/module/coverage/lcov.info # default is ./coverage/lcov.info
          # Set to true if you are running parallel jobs, then use "parallel_finished: true" for the last action.
          # parallel: # optional
          # Set to true for the last action when using "parallel: true".
          # parallel-finished: # optional
          # Coveralls Enterprise server (more info: https://enterprise.coveralls.io)
          # coveralls-endpoint: # optional, default is https://coveralls.io
          # The root folder of the project that originally ran the tests
          # base-path: # optional
