# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.0.0
        with:
          node-version: '12'
          check-latest: true
      - run: npm ci
      - run: npm test

  upload-code-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codecov/codecov-action@v1.3.2
        with:
          # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          # file: ./coverage.xml # optional
          flags: unittests # optional
          # name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)

#   automerge:
#     name: Merge pull request
#     runs-on: [ubuntu-latest]
#     needs: [test]
#     if: github.base_ref == 'master' && github.actor == 'dependabot[bot]'
#     steps:
#       - name: Merge
#         uses: actions/github-script@0.2.0
#         with:
#           script: |
#             github.pullRequests.merge({
#               owner: context.payload.repository.owner.login,
#               repo: context.payload.repository.name,
#               pull_number: context.payload.pull_request.number
#             })
#           github-token: ${{github.token}}

#                 - name: Coveralls GitHub Action
#         uses: coverallsapp/github-action@v1.1.1
#         env:
#           NODE_COVERALLS_DEBUG: 1
#         with:
#           #
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           # Path to lcov file
#           path-to-lcov: ./packages/module/coverage/lcov.info # default is ./coverage/lcov.info
#           # Set to true if you are running parallel jobs, then use "parallel_finished: true" for the last action.
#           parallel: true # optional
#           # Set to true for the last action when using "parallel: true".
#           # parallel-finished: # optional
#           # The root folder of the project that originally ran the tests
#           base-path: ./packages/module # optional
#   finish:
#     needs: test
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: packages/module
#     steps:
#       - uses: actions/checkout@v2

#       - name: Setup Node
#         uses: actions/setup-node@v1
#         with:
#           node-version: '12.x'
#       - run: npm install
#       - run: npm test
#       - name: Coveralls Finished
#         uses: coverallsapp/github-action@v1.1.1
#         env:
#           NODE_COVERALLS_DEBUG: 1
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           path-to-lcov: ./packages/module/coverage/lcov.info # default is ./coverage/lcov.info
#           base-path: ./packages/module # optional
#           parallel-finished: true

#   e2e-tests:
#     runs-on: ubuntu-latest # or macos-latest, windows-latest

#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#       - uses: microsoft/playwright-github-action@v1
#       - name: Install dependencies and run tests
#         run: npm install && node playwright.js
