# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.1
        env:
          NODE_COVERALLS_DEBUG: 1
        with:
          #
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Path to lcov file
          path-to-lcov: ./packages/module/coverage/lcov.info # default is ./coverage/lcov.info
          # Set to true if you are running parallel jobs, then use "parallel_finished: true" for the last action.
          parallel: true # optional
          # Set to true for the last action when using "parallel: true".
          # parallel-finished: # optional
          # The root folder of the project that originally ran the tests
          base-path: ./packages/module # optional
  finish:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/module
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm test
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v1.1.1
        env:
          NODE_COVERALLS_DEBUG: 1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./packages/module/coverage/lcov.info # default is ./coverage/lcov.info
          base-path: ./packages/module # optional
          parallel-finished: true
